# Generated by Django 2.0.5 on 2018-06-16 01:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_photo_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcontact',
            name='budget',
            field=models.IntegerField(choices=[(100, 100), (200, 200), (300, 300), (400, 400), (500, 500), (600, 600), (700, 700), (800, 800), (900, 900), (1000, 1000)], default=500),
        ),
        migrations.AddField(
            model_name='clientcontact',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 16, 1, 38, 37, 253515)),
        ),
    ]
