# Generated by Django 2.0.5 on 2018-06-16 01:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180616_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcontact',
            name='event_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
